DATA_PATH   = './proc.csv'
ZIP_PATH    = './util/amazon-reviews-unlocked-mobile-phones.zip'
PICKLE_PATH = './pipeline.pkl'
SIZE        = 50000
SEED        = 42
FULL_STAR   = "&#9733;"
EMPTY_STAR  = "&#9734;"
# FULL_STAR   = "\u2605"
# EMPTY_STAR  = "\u2606"
